### PR TITLE
Replace consts with customs

### PR DESCRIPTION
**Pull request by s9gf4ult**

### CODE REVIEW

**Comment by s9gf4ult** [comment]
Whoud be great to see it on melpa.

**Comment by iquiw** [comment]
I don't object to the change, but I did not suppose these values are configurable when implementing.
So something may be broken if they are customized.
Have you tested some different values?

**Comment by s9gf4ult** [comment]
Yes, I set `hyai-basic-offset` to 2 and it works well.

**Comment by iquiw** [comment]
I'm glad to hear the unexpected result 🙂 
Thanks. I will push some changes to resolve `flycheck` warnings.

**Pull request merged**
